    <div id="container">
      <div id="image"><img width="757" border="0" height="281" src="images/main.jpg"></div>
      <div id="menu">
        <ul id="nav">
<li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="index.html">Home</a> </li>
          <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="menu_aboutus.html">About Me</a>
            <ul>
<li><a href="biography.html">Biography</a></li>
              <li><a href="contact.html">Contact Me</a></li>
              <li><a href="directions.html">Directions To My Home</a></li>
            </ul>
</li>
          <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="menu_lessons.html">Lessons</a>&nbsp;
            <ul>
<li><a href="schedule_weekly_doug.html">Doug's Weekly Schedule</a></li>
              <li><a href="schedule_yearly.html">Yearly Schedule</a></li>
              <li><a href="fees.html">Fees</a></li>
              <li><a href="missed.html">Missed/Canceled Lesson Policy</a></li>
            </ul>
</li>
          <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="menu_students.html">Students</a>&nbsp;&nbsp;
            <ul>
<li><a href="recitals.html">Recitals</a></li>
              <li><a href="accomplishments.html">Accomplishments</a></li>
            </ul>
</li>
          <li>&nbsp;&nbsp;&nbsp;<a href="menu_instruments.html">Instruments</a>
            <ul>
<li><a href="repair.html">Do You Need Instrument Repair?</a></li>
              <li><a href="forsale.html">Instruments For Sale</a></li>
            </ul>
</li>
        </ul>
</div>

